### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by observerss** [sebastien/cuisine#133]
trying to pip install cuisine in py3 failed with

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/ob/.pythonbrew/pythons/Python-3.3.0/lib/python3.3/threading.py", line 639, in _bootstrap_inner
    self.run()
  File "/Users/ob/.pythonbrew/pythons/Python-3.3.0/lib/python3.3/threading.py", line 596, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ob/.virtualenvs/mastiff3/lib/python3.3/site-packages/pip-1.2.1-py3.3.egg/pip/index.py", line 245, in _get_queued_page
    page = self._get_page(location, req)
  File "/Users/ob/.virtualenvs/mastiff3/lib/python3.3/site-packages/pip-1.2.1-py3.3.egg/pip/index.py", line 337, in _get_page
    return HTMLPage.get_page(link, req, cache=self.cache)
  File "/Users/ob/.virtualenvs/mastiff3/lib/python3.3/site-packages/pip-1.2.1-py3.3.egg/pip/index.py", line 466, in get_page
    inst = cls(u(contents), real_url, headers)
  File "/Users/ob/.virtualenvs/mastiff3/lib/python3.3/site-packages/pip-1.2.1-py3.3.egg/pip/backwardcompat.py", line 44, in u
    return s.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Downloading/unpacking cuisine
  Downloading cuisine-0.5.1.tar.gz
  Running setup.py egg_info for package cuisine
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/ob/.virtualenvs/mastiff3/build/cuisine/setup.py", line 10, in <module>
        file("src/cuisine.py").readlines())[0].split("=")[1])
    NameError: name 'file' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/ob/.virtualenvs/mastiff3/build/cuisine/setup.py", line 10, in <module>

    file("src/cuisine.py").readlines())[0].split("=")[1])

NameError: name 'file' is not defined

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/ob/.virtualenvs/mastiff3/build/cuisine
Storing complete log in /Users/ob/.pip/pip.log
```

**Comment by shon** [comment]
How about using @mathiasertl 's fork? Hopefully, we can make compatible changes.

`pip install git+https://github.com/mathiasertl/fabric.git`

**Comment by sebastien** [comment]
That's an option, did you test it? I'd be happy to make some updates for Py3K compatibility

**Comment by mathiasertl** [comment]
Hey guys,

Perhaps I can shed a little light on this:

* My port is also available via pip: `pip install Fabric3`.
* Paramiko is compatible with Python3
* Upstream Fabric rejected multiple merge requests for Python3 support by me and others, because they absolutely must support Python 2.4 (!) and 2.5, which they think is still very widely used.

**Comment by sebastien** [comment]
Happy to hear it's available though `pip`. I don't understand Fabric's rationale -- who uses 2.5 these days? And even then, why not simply make a maintenance branch of Fabric -- there's no reason to be stuck in Python's middle ages.

**Comment by mathiasertl** [comment]
Wait, I just found out that since last April there now actually is an alpha vor v2: http://bitprophet.org/blog/2017/04/17/fabric-2-alpha-beta

I haven't looked at it though!

**Comment by masahitojp** [comment]
http://www.fabfile.org/changelog.html Fabric v2 is released! 
Does cuisine also correspond to Python 3?
